version: '3'

networks:
    laravel:
        driver: bridge

services:
    nginx:
        image: nginx:latest
        container_name: nginx-container
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/ssl:/etc/nginx/ssl
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        platform: linux/amd64
        image: mysql
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "${MYSQL_HOST_PORT:-3306}:${MYSQL_DOCKER_CONTAINER_PORT:-3306}"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel_docker
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./storage:/var/www/html/storage
        ports:
            - "${PHP_HOST_PORT:-9000}:${PHP_DOCKER_CONTAINER_PORT:-9000}"
        networks:
            - laravel
